--- 
name: Blob App
bbver: 4.6
sdk: /Users/vidal/code/rho_apps/rhodes
applog: C:/rholog.txt
version: 1.0
vendor: rhomobile
iphone: 
  sdk: iphonesimulator3.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug
